// <auto-generated />
using System;
using LogiPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogiPulse.Infrastructure.Migrations
{
    [DbContext(typeof(LogiPulseDbContext))]
    [Migration("20260414002101_AddUserAndEntraId")]
    partial class AddUserAndEntraId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogiPulse.Domain.Entities.Dispatches.Dispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("current_status");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_dispatches");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_dispatches_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_dispatches_tenant_id");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_dispatches_external_id_tenant_id");

                    b.ToTable("dispatches", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_products_code_tenant_id");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_products_external_id_tenant_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_product_categories");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_categories_tenant_id");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_categories_external_id_tenant_id");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("TaxCode")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_tax_code");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EntraId")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EntraId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entra_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Dispatches.Dispatch", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispatches_products_product_id");

                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("Dispatches")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispatches_tenants_tenant_id");

                    b.OwnsMany("LogiPulse.Domain.Entities.Dispatches.DispatchStatusTransition", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("DispatchId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("OccurredAtUtc");

                            b1.Property<string>("Reason");

                            b1.Property<string>("Status")
                                .IsRequired();

                            b1.HasKey("DispatchId", "__synthesizedOrdinal");

                            b1.ToTable("dispatches");

                            b1
                                .ToJson("status_history")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DispatchId")
                                .HasConstraintName("fk_dispatches_dispatches_dispatch_id");
                        });

                    b.Navigation("Product");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Products.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_products_product_categories_category_id");

                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("Products")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_tenants_tenant_id");

                    b.OwnsMany("LogiPulse.Domain.Entities.Products.ProductRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("ProductId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("Max");

                            b1.Property<string>("MetricCode")
                                .IsRequired();

                            b1.Property<decimal?>("Min");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.HasKey("ProductId", "__synthesizedOrdinal")
                                .HasName("pk_products");

                            b1.ToTable("products");

                            b1
                                .ToJson("rules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_product_id");
                        });

                    b.Navigation("Category");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.ProductCategory", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("ProductCategories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_tenants_tenant_id");

                    b.OwnsMany("LogiPulse.Domain.Entities.Products.ProductRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("ProductCategoryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("Max");

                            b1.Property<string>("MetricCode")
                                .IsRequired();

                            b1.Property<decimal?>("Min");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.HasKey("ProductCategoryId", "__synthesizedOrdinal");

                            b1.ToTable("product_categories");

                            b1
                                .ToJson("rules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductCategoryId")
                                .HasConstraintName("fk_product_categories_product_categories_product_category_id");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Navigation("Dispatches");

                    b.Navigation("ProductCategories");

                    b.Navigation("Products");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
