// <auto-generated />
using System;
using LogiPulse.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogiPulse.Infrastructure.Migrations
{
    [DbContext(typeof(LogiPulseDbContext))]
    [Migration("20260411192418_AddTenant")]
    partial class AddTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogiPulse.Domain.Entities.Dispatches.Dispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId1");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique();

                    b.ToTable("dispatches", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId1");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique();

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique();

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Dispatches.Dispatch", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("Dispatches")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LogiPulse.Domain.Entities.Dispatches.DispatchStatusTransition", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("DispatchId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("OcurredAtUtc");

                            b1.Property<string>("Reason");

                            b1.Property<string>("Status")
                                .IsRequired();

                            b1.HasKey("DispatchId", "__synthesizedOrdinal");

                            b1.ToTable("dispatches");

                            b1
                                .ToJson("StatusHistory")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DispatchId");
                        });

                    b.Navigation("Product");

                    b.Navigation("StatusHistory");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Products.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("Products")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("LogiPulse.Domain.Entities.Products.ProductRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("ProductId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("Max");

                            b1.Property<string>("MetricCode")
                                .IsRequired();

                            b1.Property<decimal?>("Min");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.HasKey("ProductId", "__synthesizedOrdinal");

                            b1.ToTable("products");

                            b1
                                .ToJson("Rules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Rules");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.ProductCategory", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("ProductCategories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("LogiPulse.Domain.Entities.Products.ProductRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("ProductCategoryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("Max");

                            b1.Property<string>("MetricCode")
                                .IsRequired();

                            b1.Property<decimal?>("Min");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.HasKey("ProductCategoryId", "__synthesizedOrdinal");

                            b1.ToTable("product_categories");

                            b1
                                .ToJson("Rules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductCategoryId");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Navigation("Dispatches");

                    b.Navigation("ProductCategories");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
