// <auto-generated />
using System;
using LogiPulse.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogiPulse.Infrastructure.Migrations
{
    [DbContext(typeof(LogiPulseDbContext))]
    [Migration("20260425163104_AddVehicles")]
    partial class AddVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogiPulse.Domain.Entities.Dispatches.Dispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("current_status");

                    b.Property<Guid>("DestinationFacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_facility_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Guid>("OriginFacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_facility_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid?>("VehicleId1")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id1");

                    b.HasKey("Id")
                        .HasName("pk_dispatches");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("ix_dispatches_current_status");

                    b.HasIndex("DestinationFacilityId")
                        .HasDatabaseName("ix_dispatches_destination_facility_id");

                    b.HasIndex("OriginFacilityId")
                        .HasDatabaseName("ix_dispatches_origin_facility_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_dispatches_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_dispatches_tenant_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_dispatches_vehicle_id");

                    b.HasIndex("VehicleId1")
                        .HasDatabaseName("ix_dispatches_vehicle_id1");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_dispatches_external_id_tenant_id");

                    b.ToTable("dispatches", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Facilities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_facilities");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_facilities_tenant_id");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_facilities_code_tenant_id");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_facilities_external_id_tenant_id");

                    b.ToTable("facilities", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_products_code_tenant_id");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_products_external_id_tenant_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_product_categories");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_product_categories_tenant_id");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_categories_external_id_tenant_id");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("TaxCode")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_tax_code");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EntraId")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EntraId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entra_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Guid?>("HomeFacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_facility_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_plate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("HomeFacilityId")
                        .HasDatabaseName("ix_vehicles_home_facility_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_vehicles_tenant_id");

                    b.HasIndex("ExternalId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_external_id_tenant_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Dispatches.Dispatch", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Facilities.Facility", "DestinationFacility")
                        .WithMany()
                        .HasForeignKey("DestinationFacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispatches_facilities_destination_facility_id");

                    b.HasOne("LogiPulse.Domain.Entities.Facilities.Facility", "OriginFacility")
                        .WithMany()
                        .HasForeignKey("OriginFacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispatches_facilities_origin_facility_id");

                    b.HasOne("LogiPulse.Domain.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispatches_products_product_id");

                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("Dispatches")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispatches_tenants_tenant_id");

                    b.HasOne("LogiPulse.Domain.Entities.Vehicles.Vehicle", null)
                        .WithMany("Dispatches")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_dispatches_vehicles_vehicle_id");

                    b.HasOne("LogiPulse.Domain.Entities.Vehicles.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId1")
                        .HasConstraintName("fk_dispatches_vehicles_vehicle_id1");

                    b.OwnsMany("LogiPulse.Domain.Entities.Dispatches.DispatchStatusTransition", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("DispatchId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("OcurredAtUtc");

                            b1.Property<string>("Reason");

                            b1.Property<string>("Status")
                                .IsRequired();

                            b1.HasKey("DispatchId", "__synthesizedOrdinal");

                            b1.ToTable("dispatches");

                            b1
                                .ToJson("status_history")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DispatchId")
                                .HasConstraintName("fk_dispatches_dispatches_dispatch_id");
                        });

                    b.Navigation("DestinationFacility");

                    b.Navigation("OriginFacility");

                    b.Navigation("Product");

                    b.Navigation("StatusHistory");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Facilities.Facility", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("Facilities")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_facilities_tenants_tenant_id");

                    b.OwnsOne("LogiPulse.Domain.Shared.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("FacilityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_complement");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("FacilityId");

                            b1.ToTable("facilities");

                            b1.WithOwner()
                                .HasForeignKey("FacilityId")
                                .HasConstraintName("fk_facilities_facilities_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Products.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_products_product_categories_category_id");

                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("Products")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_tenants_tenant_id");

                    b.OwnsMany("LogiPulse.Domain.Entities.Products.ProductRequirement", "Requirements", b1 =>
                        {
                            b1.Property<Guid>("ProductId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("Max");

                            b1.Property<string>("MetricCode")
                                .IsRequired();

                            b1.Property<decimal?>("Min");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.HasKey("ProductId", "__synthesizedOrdinal")
                                .HasName("pk_products");

                            b1.ToTable("products");

                            b1
                                .ToJson("requirements")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_product_id");
                        });

                    b.Navigation("Category");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Products.ProductCategory", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("ProductCategories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_tenants_tenant_id");

                    b.OwnsMany("LogiPulse.Domain.Entities.Products.ProductRequirement", "Requirements", b1 =>
                        {
                            b1.Property<Guid>("ProductCategoryId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<decimal?>("Max");

                            b1.Property<string>("MetricCode")
                                .IsRequired();

                            b1.Property<decimal?>("Min");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.HasKey("ProductCategoryId", "__synthesizedOrdinal");

                            b1.ToTable("product_categories");

                            b1
                                .ToJson("requirements")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductCategoryId")
                                .HasConstraintName("fk_product_categories_product_categories_product_category_id");
                        });

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.HasOne("LogiPulse.Domain.Entities.Facilities.Facility", "HomeFacility")
                        .WithMany()
                        .HasForeignKey("HomeFacilityId")
                        .HasConstraintName("fk_vehicles_facilities_home_facility_id");

                    b.HasOne("LogiPulse.Domain.Entities.Tenants.Tenant", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_tenants_tenant_id");

                    b.OwnsMany("LogiPulse.Domain.Entities.Vehicles.VehicleCapability", "Capabilities", b1 =>
                        {
                            b1.Property<Guid>("VehicleId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("IsAvailable");

                            b1.Property<decimal?>("Max");

                            b1.Property<string>("MetricCode")
                                .IsRequired();

                            b1.Property<decimal?>("Min");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.HasKey("VehicleId", "__synthesizedOrdinal");

                            b1.ToTable("vehicles");

                            b1
                                .ToJson("capabilities")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId")
                                .HasConstraintName("fk_vehicles_vehicles_vehicle_id");
                        });

                    b.Navigation("Capabilities");

                    b.Navigation("HomeFacility");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Navigation("Dispatches");

                    b.Navigation("Facilities");

                    b.Navigation("ProductCategories");

                    b.Navigation("Products");

                    b.Navigation("Users");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("LogiPulse.Domain.Entities.Vehicles.Vehicle", b =>
                {
                    b.Navigation("Dispatches");
                });
#pragma warning restore 612, 618
        }
    }
}
